### ISSUE TITLE
Display Interactive Graphs and the content generated by interactive graphs

### ISSUE THREAD

**Issue by AdinaRahim** [ExperimentalMineralPhysics/Continuous-Peak-Fit#12]
There is one interactive graph which displays against `initial_peak_position()` function call and displays output returned in response to click operations performed by user.
It is not yet supported on Windows so will need some modification to how this feature is implemented.

**Comment by aharwood2** [comment]
@AdinaRahim is this now working after the upgrade to PyQt6?

**Comment by AdinaRahim** [comment]
Yeah, its working fine at my windows laptop. Thanks @aharwood2 for bringing my attention towards PyQt6 :)

**Comment by AdinaRahim** [comment]
@aharwood2 I was running `gui_windows_setup` branch and I noticed following: 

1. Qt6 upgrades there are not supporting interactive graphs, on the contrary when I replace Qt5 imports to Qt6 imports in `gui_development` branch it support interactive graphs. 
2. Further, executing `gui_windows_setup` doesn't send gui to not responding state while loading complex graphs, on the other hand `gui_development` initially goes to not responding state while loading complex graphs

**Comment by aharwood2** [comment]
OK, well I've merged PR #32 now as you approved it. If you need to make any changes / bug fixes etc. or even if you want to downgrade PyQt to 5 again that is fine but you may want to do this on a separate feature branch with a separate issue on the tracker to monitor it. The Docker image will need updating again too.

**Comment by AdinaRahim** [comment]
> @aharwood2 I was running `gui_windows_setup` branch and I noticed following:
> 
> 1. Qt6 upgrades there are not supporting interactive graphs, on the contrary when I replace Qt5 imports to Qt6 imports in `gui_development` branch it support interactive graphs.
> 2. Further, executing `gui_windows_setup` doesn't send gui to not responding state while loading complex graphs, on the other hand `gui_development` initially goes to not responding state while loading complex graphs

Interactive graphs work on windows platform with `PyQt6` only if we execute `main.py` within `spyder IDE`.

**Comment by aharwood2** [comment]
OK, this is interesting -- any error messages as to why the graphs are not interactive when coming from the standalone wrapper?

**Comment by AdinaRahim** [comment]
> OK, this is interesting -- any error messages as to why the graphs are not interactive when coming from the standalone wrapper?

No, it doesn't throw any error and simply complete its execution the way CLI version do on windows platform by displaying empty square braces instead of picking x,y,z coordinates against click operations and displaying all interactive graphs at once instead of one by one. 

**Output:**
```
Selected points, Other (000) & Fe-BCC (110):
[
]
```

**Comment by AdinaRahim** [comment]
`plt.show(block = True) ` statement is used to block next graphs until user closes the current one, `(block = True)` doesn't seem to work on windows that's why didn't work when we use CPF CLI on windows. Surprisingly worked on windows with qt6 but seems limited to spyder and makes application unresponsive for few secs.

**Comment by AdinaRahim** [comment]
As` plt.show(block = True)` doesn't hold next graphs until we get x,y,z coordinates from click operations. I tried adding `pause` for few secs and it looks like its working fine now.

**Comment by aharwood2** [comment]
The time-based presentation of graphs is not particularly user friendly. The best thing to do here if the blocking option is not working for Matplot lib is to try to implement this manually by having a boolean flag that is set when a graph is visible and then have the main thread sleep while waiting for the flag and use a callback attached to the [figure close event](https://matplotlib.org/stable/gallery/event_handling/close_event.html) to unset the flag permitting the main thread to continue to capture the stored points and present the next graph. Alternatively, you can redesign that part of the software so the interactive part is a kind of "async task" as per other languages that can be run once and the main thread continues to loop but will only fire a new task based on the figure close event. This might be a little more complex than we have time for though, see [here](https://docs.python.org/3/library/threading.html).

**Comment by AdinaRahim** [comment]
It's been solved now by the grace of ALMIGHTY GOD !! 
and gui_development branch has been updated by [commit1](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/ac44a6c0c08f9acfc4fc6f8022210bf05bfc4847) [commit2](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/565c215bcc38549288ab6ea9a6fae462d923cf4c)
