### ISSUE TITLE
Functionalities not yet supported by CPF CLI Version

### ISSUE THREAD

**Issue by AdinaRahim** [ExperimentalMineralPhysics/Continuous-Peak-Fit#20]
This is a meta-issue that is collecting feature requests for the CPF CLI (core application). We can add issues to the CPF tracker as apporpriate at project end.

- [x] Interactive graph is not supportive on windows platform. Alternative to take input from user through free textbox?
- [x] Load Input Button functionality not clear
- [ ] Save Input Button: should write the input py file from the settings class when this button is pressed.
- [ ] Output Tab Widgets: this feature is limited a little as the example input files suggest that you can only have a single instance of each output type attached to a configuration. They also list the parameters in an un-nested way which does make it difficult to convert the data to the dictionary format in the settings class. There needs to be some more consistency here.
- [x] Sort out inline graphs (to display inline graphs in qt mode)
- [ ] Logger for `lmfit` library -- capture stdout? See #10.
- [ ] To support interactive graphs output which displays against click operation on windows platform
- [ ] Parallel processing problem on windows (execute ())
- [ ] Enable realtime data passing to each function directly from GUI (relevant to settings class)

**Comment by AdinaRahim** [comment]
**Errors: while calling execute() with parallel=False**

> TypeError: fit_sub_pattern() got an unexpected keyword argument 'intensity_threshold'

**Comments:**
could be resolved by removing/commenting `intensity_threshold` variable in `XRD_FitPattern` file in else condition which is actually executing when `parallel=False`

**Comment by AdinaRahim** [comment]
**Error while writing output for fourier_spline**

> File ~\Continuous-Peak-Fit\cpf\output_formatters\WriteDifferentialStrain.py:268 in WriteOutput
>     raise ValueError(
> 
> ValueError: This output type is not setup to process non-Fourier peak centroids.

**Comment by AdinaRahim** [comment]
File ~\Continuous-Peak-Fit\cpf\fitsubpattern_chunks.py:619 in fit_series
    symmetry = orders["peak"][j]["symmetry"]

**KeyError:** 'symmetry'

**Comment by AdinaRahim** [comment]
Error while running `BCC1_input_Dioptas_fourier_spline` 

 ```
File "C:\Users\g05296ar\Continuous-Peak-Fit\cpf\settings.py", line 263, in read_settings_file
    self.data_class = detector_factory(fit_settings=self)
  File "C:\Users\g05296ar\Continuous-Peak-Fit\cpf\settings.py", line 1019, in detector_factory
    return detector_class(settings_class=fit_settings)
  File "C:\Users\g05296ar\Continuous-Peak-Fit\cpf\input_types\DioptasFunctions.py", line 49, in __init__
    self.detector = self.get_detector(settings=settings_class)
  File "C:\Users\g05296ar\Continuous-Peak-Fit\cpf\input_types\DioptasFunctions.py", line 97, in get_detector
    im_all = fabio.open(diff_file)
```

**Commnets:**
CPF doesn't work until we specify value for  `Calib_detector` variable e.g., Calib_detector = 'Pilatus1M'`.
Uncommenting this variable make this input file work

**Comment by aharwood2** [comment]
> **Simon's To Do List:** Based on today's (01/Dec/2022) meeting notes:
> 
> * [x]  Sort out inline graphs (to display inline graphs in qt mode)
> * [ ]  Implement Save button functionality to generate same layout of input file
> * [ ]  Logger for limfit library
> * [ ]  To support interactive graphs output which displays against click operation on windows platform
> * [ ]  Parallel processing problem on windows (execute ())
> * [ ]  Enable realtime data passing to each function directly from GUI (relevant to settings class)

I suggest merging this list of tasks into the issue description so they are all in one place rather than having multiple lists in the same issue. Plus, the tasks in the description are automatically tracked on the issue header.

**Comment by aharwood2** [comment]
Started to compile a general list of improvements to core and to GUI on one issue for now so I'll close this and we can just continue to build on #33.
