### ISSUE TITLE
Create Save Inputs Button

### ISSUE THREAD

**Issue by AdinaRahim** [ExperimentalMineralPhysics/Continuous-Peak-Fit#22]
This issue represents the meta-task of writing out the contents of the GUI to the input file.

The missing feature is to be able to take the settings class and write out the contents into a file format that matches the input files: #20 (point 3).

This issue should be able to take an existing input file that has been opened into the GUI using the load button and write out an input file that is identical to the one that has been read in.

**Comment by aharwood2** [comment]
The save button should just ask a method to take the settings class and write it out since the settings class is kept in sync with the GUI via the events that fire when the GUI elements are updated by the user.

**Comment by S-Hunt** [comment]
I have added a function to the settings class and file that (when completed) enables the writing of the data class to a file. Currently it is only a place holder but I can fix this later

**Comment by AdinaRahim** [comment]
At the moment this function [(save_settings)](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/ef9a0327ad61531fa579b5ad53dc3c55c3f13a10) is dumping nothing into json file so no custom input files are created by it at the moment. 

> Default serializer/encoder is missing

**Comment by AdinaRahim** [comment]
It's been done in final [commit](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/79794e4b70f57f1e575e512bceb1d5f38d1869c8) apart from above mentioned errors that are arising due to missing functionality in CPF CLI version. Couldn't test how it reacts after dumping data into json file but no error is arising in our `save_button` function

**Comment by AdinaRahim** [comment]
> At the moment this function [(save_settings)](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/ef9a0327ad61531fa579b5ad53dc3c55c3f13a10) is dumping nothing into json file so no custom input files are created by it at the moment.
> 
> function definition for specified default serializer/encoder is missing. keeping specified default value raises following error:
> 
> **NameError:** `name 'json_numpy_serializer' is not defined`
> 
> while commenting it raise following error:
> 
> **TypeError:** `Object of type settings is not JSON serializable`

**Comments:**
It was due to missing import, now sorted in [commit](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/3fdcd8632886a54f563377547e804e9a4122cf11)
