### ISSUE TITLE
Fix Save_Inputs Errors by changing Datatypes in settings class

### ISSUE THREAD

**Issue by AdinaRahim** [ExperimentalMineralPhysics/Continuous-Peak-Fit#35]
We need to change datatype of fit_orders variable defined in settings class which is initialized with none and becoming the root cause of two errors :

1. NoneType is not subscriptable
2. List index out of range

@S-Hunt  suggested initializing it as follows:
```
self.fit_orders = [{
          "range": [[1,2]],
          "background": [0, 0],
          "peak": [{
              "phase": "none",
              "hkl": "000",
              "d-space": 0,
              "height": 0,
              "profile": 0,
              "width": 0,
              "symmetry": 2
            }],
        },]
```
**while doing this doesn't seem to deal with `list out of index error` because we have added only one item in the list so whenever we try to insert second Range_Tabs it tries to initialize the values in second item of self.fit_orders in settings class which actually doesn't exist in return it throws `list out of index error`. Other solutions could be:**

- [x] make self.fit_orders an empty list [Done](https://github.com/ExperimentalMineralPhysics/Continuous-Peak-Fit/commit/ba6e5ec84ef0c2275135df3b2aff91269cfe01ac)
- [x] While NoneType not subscriptable can be resolved by replacing **none** with empty string e.g., `"phase": " " `
- [x] append following into settings class (`self.fit_orders = []` ) variable everytime Range_Tab is inserted in GUI 
```
        {
          "range": [[1,2]],
          "background": [0, 0],
          "peak": [],
        },)
```

- [x] append following into settings class (`self.fit_orders = [{"peak": []}` ) variable everytime new Peak_Tab is inserted within Range_Tab 
```
      {
           "phase": "",
           "hkl": "000",
           "d-space": 0,
           "d-space-type":"",
           "height": 0,
           "height-type":"",
           "height_fixed":"",
           "profile": 0,
           "profile-type": "",
           "profile_fixed": "",
           "width": 0,
           "width-type":"",
           "width_fixed":"",
           "symmetry": 2
      }
```

**Comment by aharwood2** [comment]
Done now and commited to GUI dev branch.
